import type { Agent } from '../types'

// Skill content resolved from a skill reference (e.g., "org/skill@v1")
export type ResolvedSkill = {
  ref: string         // Original reference, e.g., "org/skill@v1"
  name: string
  description?: string
  prompt: string
}

// The canonical agent data from orchagent
export type CanonicalAgent = Agent & {
  org_slug: string
  resolvedSkills?: ResolvedSkill[]
}

// Content types that can be converted
export type ContentType = 'prompt' | 'skill' | 'code'

// Result of conversion compatibility check
export interface ConversionResult {
  canConvert: boolean
  warnings: string[] // e.g., "tools field not supported"
  errors: string[] // e.g., "code agents cannot be converted"
}

// A file generated by an adapter
export interface ConvertedFile {
  filename: string // e.g., "code-reviewer.md"
  content: string // The file content
  installPath: string // Relative path, e.g., ".claude/agents/"
}

// Installation path options
export interface InstallPath {
  scope: 'user' | 'project'
  path: string // Full path template, e.g., "~/.claude/agents/" or ".claude/agents/"
  description: string // Human-readable description
}

// The core adapter interface
export interface FormatAdapter {
  // Metadata
  id: string // e.g., "claude-code", "cursor", "agents-md"
  name: string // e.g., "Claude Code Sub-Agent"
  version: string // Adapter version (e.g., "1.0.0")
  formatVersion: string // Target format version (e.g., "2026-01")

  // What this adapter supports
  supportedTypes: ContentType[] // ['prompt', 'skill'] - code agents typically can't be converted

  // Installation paths
  installPaths: InstallPath[]

  // Core methods
  canConvert(agent: CanonicalAgent): ConversionResult
  convert(agent: CanonicalAgent): ConvertedFile[]

  // Optional: validation
  validate?(content: string): ValidationResult
}

// Validation result for checking generated content
export interface ValidationResult {
  valid: boolean
  errors: string[]
  warnings: string[]
}
