import { Command, Option } from 'commander'

// --- Types ---

interface OptionMeta {
  long: string | null
  short: string | null
  description: string
}

interface SubcommandMeta {
  name: string
  description: string
  options: OptionMeta[]
}

interface CommandMeta {
  name: string
  description: string
  options: OptionMeta[]
  subcommands: SubcommandMeta[]
}

// --- Extraction ---

function extractOptions(opts: readonly Option[]): OptionMeta[] {
  return opts.map((o) => ({
    long: o.long ?? null,
    short: o.short ?? null,
    description: o.description,
  }))
}

export function extractCommands(program: Command): CommandMeta[] {
  return program.commands
    .filter((cmd) => cmd.name() !== 'completion')
    .map((cmd) => ({
      name: cmd.name(),
      description: cmd.description(),
      options: extractOptions(cmd.options),
      subcommands: cmd.commands.map((sub) => ({
        name: sub.name(),
        description: sub.description(),
        options: extractOptions(sub.options),
      })),
    }))
}

function extractGlobalOptions(program: Command): OptionMeta[] {
  return extractOptions(program.options)
}

// --- Helpers ---

function longFlags(opts: OptionMeta[]): string[] {
  return opts.filter((o) => o.long).map((o) => o.long!)
}

/** Escape single quotes for embedding in shell strings */
function esc(s: string): string {
  return s.replace(/'/g, "'\\''")
}

// --- Bash ---

export function generateBash(commands: CommandMeta[], globalOptions: OptionMeta[]): string {
  const allNames = commands.map((c) => c.name).join(' ')
  const globalFlags = [...longFlags(globalOptions), '--help', '--version'].join(' ')

  // Build option-completion case arms
  const optionArms: string[] = []
  for (const cmd of commands) {
    const flags = [...longFlags(cmd.options), '--help'].join(' ')

    if (cmd.subcommands.length > 0) {
      const subArms: string[] = []
      for (const sub of cmd.subcommands) {
        const subFlags = [...longFlags(sub.options), '--help'].join(' ')
        subArms.push(`            ${sub.name}) opts="${subFlags}" ;;`)
      }
      subArms.push('            *) opts="--help" ;;')
      optionArms.push(
        [
          `        ${cmd.name})`,
          '          case "$subcmd" in',
          ...subArms,
          '          esac',
          '          ;;',
        ].join('\n')
      )
    } else {
      optionArms.push(`        ${cmd.name}) opts="${flags}" ;;`)
    }
  }

  // Build subcommand-completion case arms
  const subArms: string[] = []
  for (const cmd of commands) {
    if (cmd.subcommands.length > 0) {
      const names = cmd.subcommands.map((s) => s.name).join(' ')
      subArms.push(`    ${cmd.name}) COMPREPLY=($(compgen -W "${names}" -- "$cur")) ;;`)
    }
  }

  const lines = [
    '# orch shell completions — generated by: orch completion bash',
    '#',
    '# Setup (pick one):',
    '#   eval "$(orch completion bash)"                                    # add to ~/.bashrc',
    '#   orch completion bash > ~/.local/share/bash-completion/completions/orch  # persistent',
    '',
    '_orch() {',
    '  local cur cmd subcmd i',
    '  COMPREPLY=()',
    '  cur="${COMP_WORDS[COMP_CWORD]}"',
    '',
    '  cmd=""',
    '  subcmd=""',
    '  for ((i=1; i < COMP_CWORD; i++)); do',
    '    case "${COMP_WORDS[i]}" in',
    '      -*) ;;',
    '      *)',
    '        if [[ -z "$cmd" ]]; then',
    '          cmd="${COMP_WORDS[i]}"',
    '        elif [[ -z "$subcmd" ]]; then',
    '          subcmd="${COMP_WORDS[i]}"',
    '        fi',
    '        ;;',
    '    esac',
    '  done',
    '',
    '  if [[ "$cur" == -* ]]; then',
    '    local opts=""',
    '    if [[ -z "$cmd" ]]; then',
    `      opts="${globalFlags}"`,
    '    else',
    '      case "$cmd" in',
    ...optionArms,
    '        *) opts="--help" ;;',
    '      esac',
    '    fi',
    '    COMPREPLY=($(compgen -W "$opts" -- "$cur"))',
    '    return 0',
    '  fi',
    '',
    '  if [[ -z "$cmd" ]]; then',
    `    COMPREPLY=($(compgen -W "${allNames}" -- "$cur"))`,
    '    return 0',
    '  fi',
    '',
    '  case "$cmd" in',
    ...subArms,
    '  esac',
    '}',
    '',
    'complete -o default -F _orch orch',
    'complete -o default -F _orch orchagent',
    '',
  ]

  return lines.join('\n')
}

// --- Zsh ---

export function generateZsh(commands: CommandMeta[], globalOptions: OptionMeta[]): string {
  // Build command descriptions for _describe
  const cmdDescriptions = commands
    .map((c) => `    '${esc(c.name)}:${esc(c.description)}'`)
    .join('\n')

  // Build global option specs for _arguments
  const globalOptSpecs: string[] = []
  for (const opt of globalOptions) {
    if (opt.long) {
      globalOptSpecs.push(`    '${esc(opt.long)}[${esc(opt.description)}]'`)
    }
  }
  globalOptSpecs.push("    '(--help -h)'{--help,-h}'[Show help]'")
  globalOptSpecs.push("    '(--version -V)'{--version,-V}'[Show version]'")

  // Build per-command argument completions
  const commandCases: string[] = []
  for (const cmd of commands) {
    if (cmd.subcommands.length > 0) {
      // Subcommand group
      const subDescs = cmd.subcommands
        .map((s) => `          '${esc(s.name)}:${esc(s.description)}'`)
        .join('\n')

      const subArgsCases: string[] = []
      for (const sub of cmd.subcommands) {
        const subOpts: string[] = []
        for (const opt of sub.options) {
          if (opt.long) {
            subOpts.push(`              '${esc(opt.long)}[${esc(opt.description)}]'`)
          }
        }
        subOpts.push("              '(--help -h)'{--help,-h}'[Show help]'")
        subArgsCases.push(
          [
            `            ${sub.name})`,
            '              _arguments \\',
            subOpts.join(' \\\n'),
            '              ;;',
          ].join('\n')
        )
      }

      commandCases.push(
        [
          `        ${cmd.name})`,
          '          local -a subcmds=(',
          subDescs,
          '          )',
          '          _arguments -C \\',
          "            '1:subcommand:->subcmd' \\",
          "            '*::subarg:->subargs'",
          '          case $state in',
          '            subcmd)',
          "              _describe -t subcommands 'subcommand' subcmds",
          '              ;;',
          '            subargs)',
          '              case $line[1] in',
          ...subArgsCases,
          '                *)',
          '                  _arguments \\',
          "                    '(--help -h)'{--help,-h}'[Show help]'",
          '                  ;;',
          '              esac',
          '              ;;',
          '          esac',
          '          ;;',
        ].join('\n')
      )
    } else {
      // Simple command
      const cmdOpts: string[] = []
      for (const opt of cmd.options) {
        if (opt.long) {
          cmdOpts.push(`          '${esc(opt.long)}[${esc(opt.description)}]'`)
        }
      }
      cmdOpts.push("          '(--help -h)'{--help,-h}'[Show help]'")
      commandCases.push(
        [
          `        ${cmd.name})`,
          '          _arguments \\',
          cmdOpts.join(' \\\n'),
          '          ;;',
        ].join('\n')
      )
    }
  }

  const lines = [
    '#compdef orch orchagent',
    '#',
    '# orch shell completions — generated by: orch completion zsh',
    '#',
    '# Setup (pick one):',
    '#   eval "$(orch completion zsh)"                    # add to ~/.zshrc',
    '#   orch completion zsh > "${fpath[1]}/_orch"        # persistent (then compinit)',
    '',
    '_orch() {',
    '  local context state state_descr line',
    '  typeset -A opt_args',
    '',
    '  local -a commands=(',
    cmdDescriptions,
    '  )',
    '',
    '  _arguments -C \\',
    globalOptSpecs.join(' \\\n'),
    " \\",
    "    '1:command:->command' \\",
    "    '*::arg:->args'",
    '',
    '  case $state in',
    '    command)',
    "      _describe -t commands 'orch command' commands",
    '      ;;',
    '    args)',
    '      case $line[1] in',
    ...commandCases,
    '        *)',
    '          _arguments \\',
    "            '(--help -h)'{--help,-h}'[Show help]'",
    '          ;;',
    '      esac',
    '      ;;',
    '  esac',
    '}',
    '',
    '_orch "$@"',
    '',
  ]

  return lines.join('\n')
}

// --- Fish ---

export function generateFish(commands: CommandMeta[], globalOptions: OptionMeta[]): string {
  const lines: string[] = [
    '# orch shell completions — generated by: orch completion fish',
    '#',
    '# Setup (pick one):',
    '#   orch completion fish | source                                          # add to config.fish',
    '#   orch completion fish > ~/.config/fish/completions/orch.fish            # persistent',
    '',
    '# Disable file completions by default',
    'complete -c orch -f',
    'complete -c orchagent -f',
    '',
    '# Global options',
  ]

  for (const opt of globalOptions) {
    if (opt.long) {
      const flag = opt.long.replace(/^--/, '')
      lines.push(`complete -c orch -l ${flag} -d '${esc(opt.description)}'`)
      lines.push(`complete -c orchagent -l ${flag} -d '${esc(opt.description)}'`)
    }
  }
  lines.push("complete -c orch -l help -d 'Show help'")
  lines.push("complete -c orchagent -l help -d 'Show help'")
  lines.push("complete -c orch -l version -d 'Show version'")
  lines.push("complete -c orchagent -l version -d 'Show version'")

  lines.push('')
  lines.push('# Commands')

  for (const cmd of commands) {
    lines.push(
      `complete -c orch -n '__fish_use_subcommand' -a ${cmd.name} -d '${esc(cmd.description)}'`
    )
    lines.push(
      `complete -c orchagent -n '__fish_use_subcommand' -a ${cmd.name} -d '${esc(cmd.description)}'`
    )
  }

  // Subcommands for command groups
  const groups = commands.filter((c) => c.subcommands.length > 0)
  if (groups.length > 0) {
    lines.push('')
    lines.push('# Subcommands')

    for (const cmd of groups) {
      const subNames = cmd.subcommands.map((s) => s.name)
      const notSeen = subNames.join(' ')
      for (const sub of cmd.subcommands) {
        const cond = `__fish_seen_subcommand_from ${cmd.name}; and not __fish_seen_subcommand_from ${notSeen}`
        lines.push(
          `complete -c orch -n '${cond}' -a ${sub.name} -d '${esc(sub.description)}'`
        )
        lines.push(
          `complete -c orchagent -n '${cond}' -a ${sub.name} -d '${esc(sub.description)}'`
        )
      }
    }
  }

  // Options per command
  const commandsWithOptions = commands.filter((c) => c.options.length > 0 && c.subcommands.length === 0)
  if (commandsWithOptions.length > 0) {
    lines.push('')
    lines.push('# Command options')

    for (const cmd of commandsWithOptions) {
      for (const opt of cmd.options) {
        if (opt.long) {
          const flag = opt.long.replace(/^--/, '')
          lines.push(
            `complete -c orch -n '__fish_seen_subcommand_from ${cmd.name}' -l ${flag} -d '${esc(opt.description)}'`
          )
          lines.push(
            `complete -c orchagent -n '__fish_seen_subcommand_from ${cmd.name}' -l ${flag} -d '${esc(opt.description)}'`
          )
        }
      }
    }
  }

  // Options for subcommand groups (on the group level)
  const groupsWithOpts = commands.filter((c) => c.subcommands.length > 0)
  const subOptsNeeded = groupsWithOpts.some((g) => g.subcommands.some((s) => s.options.length > 0))
  if (subOptsNeeded) {
    lines.push('')
    lines.push('# Subcommand options')

    for (const cmd of groupsWithOpts) {
      for (const sub of cmd.subcommands) {
        for (const opt of sub.options) {
          if (opt.long) {
            const flag = opt.long.replace(/^--/, '')
            lines.push(
              `complete -c orch -n '__fish_seen_subcommand_from ${cmd.name}; and __fish_seen_subcommand_from ${sub.name}' -l ${flag} -d '${esc(opt.description)}'`
            )
            lines.push(
              `complete -c orchagent -n '__fish_seen_subcommand_from ${cmd.name}; and __fish_seen_subcommand_from ${sub.name}' -l ${flag} -d '${esc(opt.description)}'`
            )
          }
        }
      }
    }
  }

  lines.push('')
  return lines.join('\n')
}

// --- Dispatcher ---

const SUPPORTED_SHELLS = ['bash', 'zsh', 'fish'] as const
type Shell = (typeof SUPPORTED_SHELLS)[number]

export function generateCompletion(shell: string, program: Command): string {
  const commands = extractCommands(program)
  const globalOptions = extractGlobalOptions(program)

  switch (shell) {
    case 'bash':
      return generateBash(commands, globalOptions)
    case 'zsh':
      return generateZsh(commands, globalOptions)
    case 'fish':
      return generateFish(commands, globalOptions)
    default:
      throw new Error(
        `Unsupported shell: ${shell}. Supported shells: ${SUPPORTED_SHELLS.join(', ')}`
      )
  }
}

// --- Command Registration ---

export function registerCompletionCommand(program: Command): void {
  program
    .command('completion')
    .argument('<shell>', `Shell type (${SUPPORTED_SHELLS.join(', ')})`)
    .description('Generate shell completion script')
    .addHelpText(
      'after',
      `
Examples:
  orch completion bash    Generate bash completions
  orch completion zsh     Generate zsh completions
  orch completion fish    Generate fish completions

Setup:
  eval "$(orch completion bash)"                                    # bash (add to ~/.bashrc)
  eval "$(orch completion zsh)"                                     # zsh  (add to ~/.zshrc)
  orch completion fish | source                                     # fish (add to config.fish)
`
    )
    .action((shell: string) => {
      const script = generateCompletion(shell, program)
      process.stdout.write(script)
    })
}
